### ISSUE TITLE
Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

### ISSUE THREAD

**Issue by eusthace** [MetaMask/vault-decryptor#7]
Can't decrypt my vault using this tool. Getting this error all the time:

`
Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at Object.base64ToBuffer (http://localhost:8000/bundle.js:1179:16)
    at keyFromPassword (http://localhost:8000/bundle.js:1040:29)
    at Object.decrypt (http://localhost:8000/bundle.js:1017:10)
    at AppRoot.decrypt (http://localhost:8000/bundle.js:893:14)
    at HTMLUnknownElement.boundFunc (http://localhost:8000/bundle.js:13702:9)
    at Object.ReactErrorUtils.invokeGuardedCallback (http://localhost:8000/bundle.js:13708:16)
    at executeDispatch (http://localhost:8000/bundle.js:7725:21)
    at Object.executeDispatchesInOrder (http://localhost:8000/bundle.js:7748:5)
    at executeDispatchesAndRelease (http://localhost:8000/bundle.js:7156:22)
    at executeDispatchesAndReleaseTopLevel (http://localhost:8000/bundle.js:7167:10)
`

Any help, please?

**Comment by mcmire** [comment]
This seems like an old issue, so I'm going to close this.
